import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} mx-7 mt-5 flex gap-8 bg-white-100`}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
